### ISSUE TITLE
Flood protection doesn't segment threaded conversation

### ISSUE THREAD

**Issue by jszmajda** [jszmajda/dctech-hubot#2]
I would like threads to have their own flood protection configuration (if any at all). I'll need to figure out how to differentiate messages in threads from the main channel. The `hubot-slack` adapter appears to have some concept of threads already, see this: https://github.com/slackapi/hubot-slack/pull/398/files

**Comment by yarmiganosca** [comment]
Doc links:
* http://slackapi.github.io/hubot-slack/basic_usage#messages-directed-to-your-bot
* https://api.slack.com/docs/message-threading

It seems like, based on those docs, that the `thread_ts` attribute of a message in a thread is a "unique" identifier for that thread, which would let you do per-thread rate limiting.

To be fair though, I didn't find those docs very clear on whether `thread_ts` is the ultimate parent, or just the immediate parent, so maybe I'm completely wrong!

**Comment by jszmajda** [comment]
I actually rather like the behavior as it is so I'm going to close this :)
